services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/var/www/html
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/
      - ./default.conf:/etc/nginx/nginx.conf
    links:
      - app
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: php_mvc
        MYSQL_USER: php_mvc
        MYSQL_PASSWORD: php_mvc

volumes:
  mysql-data: